set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind \\ split-window -h
bind - split-window -v
unbind '"'
unbind %

bind r command-prompt -I'#W' { rename-window -- '%%' }

set -g @catppuccin_flavour 'mocha'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'

# set vi-mode
set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# bg="#3B4252"
# # bg="default"
# # default_fg="#ECEFF4"
# default_fg="#D8DEE9" 
# # default_fg="E5E9F0" 
# session_fg="#A3BE8C"
# selection_bg="#81A1C1"
# selection_fg="#3B4252"
# active_pane_border="#abb2bf"
# active_window_fg="#A3BE8C"
# active_window_fg="#88C0D0"

# set -g status-position bottom
# set -g status-left "#[fg=${session_fg},bold,bg=${bg}]  #S"
# set -g status-right " #{cpu -i 3} |  #{mem} "
# set -g status-justify centre
# set -g status-left-length 20   # default: 10
# set -g status-right-length 20  # default: 10
# set-option -g status-style bg=${bg}
# set -g window-status-current-format "#[fg=${active_window_fg},bg=default]  #I:#W"
# set -g window-status-format "#[fg=${default_fg},bg=default] #I:#W"
# set -g window-status-last-style "fg=${default_fg},bg=default"
# set -g message-command-style bg=default,fg=${default_fg}
# set -g message-style bg=default,fg=${default_fg}
# set -g mode-style bg=${selection_bg},fg=${selection_fg}
# set -g pane-active-border-style "fg=${active_pane_border},bg=default"
# set -g pane-border-style 'fg=brightblack,bg=default'
